// GENERATED by gtm-apply from a Tag Manager container. Do not edit; run the package's pull script.
export const data = {
  data: {
    pulledAt: "2026-09-27T23:03:13.507Z",
    source: {
      container: "GTM-TPLKC7QP",
    },
    container: {
      path: "accounts/6004731770/containers/263680884",
      accountId: "6004731770",
      containerId: "263680884",
      name: "Template - Web",
      publicId: "GTM-TPLKC7QP",
      usageContext: ["web"],
      fingerprint: "1790390525466",
      tagManagerUrl:
        "https://tagmanager.google.com/#/container/accounts/6004731770/containers/263680884/workspaces?apiLink=container",
      features: {
        supportUserPermissions: true,
        supportEnvironments: true,
        supportWorkspaces: true,
        supportGtagConfigs: false,
        supportBuiltInVariables: true,
        supportClients: false,
        supportFolders: true,
        supportTags: true,
        supportTemplates: true,
        supportTriggers: true,
        supportVariables: true,
        supportVersions: true,
        supportZones: true,
        supportTransformations: false,
      },
      tagIds: ["GTM-TPLKC7QP"],
    },
    containerType: "web",
    environments: [
      {
        path: "accounts/6004731770/containers/263680884/environments/1",
        accountId: "6004731770",
        containerId: "263680884",
        environmentId: "1",
        type: "live",
        fingerprint: "1788972850209",
        name: "Live",
        description: "This environment points to the currently published version.",
        authorizationCode: "hwh5NvDZ-pr6QgB8Id5ozw",
        authorizationTimestamp: "2026-09-09T16:54:10.209Z",
        tagManagerUrl:
          "https://tagmanager.google.com/#/admin/accounts/6004731770/containers/263680884/environments?apiLink=environment",
      },
      {
        path: "accounts/6004731770/containers/263680884/environments/2",
        accountId: "6004731770",
        containerId: "263680884",
        environmentId: "2",
        type: "latest",
        fingerprint: "1788972850209",
        name: "Latest",
        description: "This environment points to the latest created version.",
        authorizationCode: "th2hvOYwVciz7d4eO6Eh8g",
        authorizationTimestamp: "2026-09-09T16:54:10.209Z",
        tagManagerUrl:
          "https://tagmanager.google.com/#/admin/accounts/6004731770/containers/263680884/environments?apiLink=environment",
      },
    ],
    destinations: [],
    workspace: null,
    containerVersionHeader: {
      path: "accounts/6004731770/containers/263680884/versions/4",
      accountId: "6004731770",
      containerId: "263680884",
      containerVersionId: "4",
      name: "recipes-2026-09-27",
      numTags: "9",
      numTriggers: "4",
      numVariables: "11",
    },
    environment: null,
    folder: [],
    variable: [
      {
        accountId: "6004731770",
        containerId: "263680884",
        variableId: "3",
        name: "Library - Manifest",
        type: "c",
        parameter: [
          {
            type: "template",
            key: "value",
            value:
              '{"conventions":{},"recipes":{"google_tag":{"description":"Google tag on Initialization; base for every recipe."},"contact_form_submit":{"description":"Contact form submitted (dataLayer event).","dependencies":[{"constant":"Const - Google Ads - contact_form_submit Conversion Label","platform":"googleAds","resource":"conversionAction"}]},"call_click":{"description":"tel: link clicked.","dependencies":[{"constant":"Const - Google Ads - call_click Conversion Label","platform":"googleAds","resource":"conversionAction"}]},"email_click":{"description":"mailto: link clicked.","dependencies":[{"constant":"Const - Google Ads - email_click Conversion Label","platform":"googleAds","resource":"conversionAction"}]},"maps_click":{"description":"Google Maps link clicked.","dependencies":[{"constant":"Const - Google Ads - maps_click Conversion Label","platform":"googleAds","resource":"conversionAction"}]}}}',
          },
        ],
        fingerprint: "1790550048304",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        variableId: "4",
        name: "Const - GA4 Measurement ID",
        type: "c",
        notes:
          'Measurement ID of the site\'s GA4 web data stream (Admin > Data streams).\n---\n{"placeholder":{"kind":"ga4MeasurementId","example":"G-ABC123DEF4","pattern":"^G-[A-Z0-9]+$"}}',
        parameter: [
          {
            type: "template",
            key: "value",
            value: "<G-XXXXXXXXXX>",
          },
        ],
        fingerprint: "1790550053352",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        variableId: "5",
        name: "Const - Google Ads Conversion ID",
        type: "c",
        notes:
          'The bare numeric conversion id (the digits after AW- in Google Ads). GTM stores it without the prefix; the conversion tag builds AW-<id>/<label> itself.\n---\n{"placeholder":{"kind":"adsConversionId","example":"123456789","pattern":"^[0-9]+$"}}',
        parameter: [
          {
            type: "template",
            key: "value",
            value: "<XXXXXXXXX>",
          },
        ],
        fingerprint: "1790550058311",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        variableId: "6",
        name: "Const - Google Ads - contact_form_submit Conversion Label",
        type: "c",
        notes:
          'Conversion label of the Google Ads conversion action for contact_form_submit.\n---\n{"placeholder":{"kind":"adsConversionLabel","example":"AbCdEfGhIjKlMnOp","pattern":"^[A-Za-z0-9_-]{5,}$"}}',
        parameter: [
          {
            type: "template",
            key: "value",
            value: "<label>",
          },
        ],
        fingerprint: "1790550063342",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        variableId: "7",
        name: "Const - Google Ads - call_click Conversion Label",
        type: "c",
        notes:
          'Conversion label of the Google Ads conversion action for call_click.\n---\n{"placeholder":{"kind":"adsConversionLabel","example":"AbCdEfGhIjKlMnOp","pattern":"^[A-Za-z0-9_-]{5,}$"}}',
        parameter: [
          {
            type: "template",
            key: "value",
            value: "<label>",
          },
        ],
        fingerprint: "1790550068307",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        variableId: "8",
        name: "Const - Google Ads - email_click Conversion Label",
        type: "c",
        notes:
          'Conversion label of the Google Ads conversion action for email_click.\n---\n{"placeholder":{"kind":"adsConversionLabel","example":"AbCdEfGhIjKlMnOp","pattern":"^[A-Za-z0-9_-]{5,}$"}}',
        parameter: [
          {
            type: "template",
            key: "value",
            value: "<label>",
          },
        ],
        fingerprint: "1790550073325",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        variableId: "9",
        name: "Const - Google Ads - maps_click Conversion Label",
        type: "c",
        notes:
          'Conversion label of the Google Ads conversion action for maps_click.\n---\n{"placeholder":{"kind":"adsConversionLabel","example":"AbCdEfGhIjKlMnOp","pattern":"^[A-Za-z0-9_-]{5,}$"}}',
        parameter: [
          {
            type: "template",
            key: "value",
            value: "<label>",
          },
        ],
        fingerprint: "1790550078362",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        variableId: "10",
        name: "DLV - form_id",
        type: "v",
        notes: "The submitted form's id, read from the dataLayer.",
        parameter: [
          {
            type: "template",
            key: "name",
            value: "form_id",
          },
        ],
        fingerprint: "1790550083351",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        variableId: "11",
        name: "DLV - form_name",
        type: "v",
        notes: "The submitted form's name, read from the dataLayer.",
        parameter: [
          {
            type: "template",
            key: "name",
            value: "form_name",
          },
        ],
        fingerprint: "1790550088334",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        variableId: "12",
        name: "DLV - form_destination",
        type: "v",
        notes: "The submitted form's destination URL, read from the dataLayer.",
        parameter: [
          {
            type: "template",
            key: "name",
            value: "form_destination",
          },
        ],
        fingerprint: "1790550093359",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        variableId: "13",
        name: "DLV - form_submit_text",
        type: "v",
        notes: "The submit button's text, read from the dataLayer.",
        parameter: [
          {
            type: "template",
            key: "name",
            value: "form_submit_text",
          },
        ],
        fingerprint: "1790550098311",
      },
    ],
    trigger: [
      {
        accountId: "6004731770",
        containerId: "263680884",
        triggerId: "14",
        name: "Custom Event - contact_form_submit",
        type: "customEvent",
        customEventFilter: [
          {
            type: "equals",
            parameter: [
              {
                type: "template",
                key: "arg0",
                value: "{{_event}}",
              },
              {
                type: "template",
                key: "arg1",
                value: "contact_form_submit",
              },
            ],
          },
        ],
        fingerprint: "1790550103404",
        notes:
          "Fires on the dataLayer event contact_form_submit that the site's form handler pushes on a successful submit.",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        triggerId: "15",
        name: "Click - call",
        type: "linkClick",
        filter: [
          {
            type: "contains",
            parameter: [
              {
                type: "template",
                key: "arg0",
                value: "{{Click URL}}",
              },
              {
                type: "template",
                key: "arg1",
                value: "tel:",
              },
            ],
          },
        ],
        autoEventFilter: [
          {
            type: "matchRegex",
            parameter: [
              {
                type: "template",
                key: "arg0",
                value: "{{Page URL}}",
              },
              {
                type: "template",
                key: "arg1",
                value: ".*",
              },
            ],
          },
        ],
        waitForTags: {
          type: "boolean",
          value: "true",
        },
        checkValidation: {
          type: "boolean",
          value: "false",
        },
        waitForTagsTimeout: {
          type: "template",
          value: "2000",
        },
        uniqueTriggerId: {
          type: "template",
        },
        fingerprint: "1790550108351",
        notes:
          "Fires on a click of a tel: link. Contains, not starts-with, so a swapped forwarding number still matches.",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        triggerId: "16",
        name: "Click - email",
        type: "linkClick",
        filter: [
          {
            type: "contains",
            parameter: [
              {
                type: "template",
                key: "arg0",
                value: "{{Click URL}}",
              },
              {
                type: "template",
                key: "arg1",
                value: "mailto:",
              },
            ],
          },
        ],
        autoEventFilter: [
          {
            type: "matchRegex",
            parameter: [
              {
                type: "template",
                key: "arg0",
                value: "{{Page URL}}",
              },
              {
                type: "template",
                key: "arg1",
                value: ".*",
              },
            ],
          },
        ],
        waitForTags: {
          type: "boolean",
          value: "true",
        },
        checkValidation: {
          type: "boolean",
          value: "false",
        },
        waitForTagsTimeout: {
          type: "template",
          value: "2000",
        },
        uniqueTriggerId: {
          type: "template",
        },
        fingerprint: "1790550113359",
        notes: "Fires on a click of a mailto: link.",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        triggerId: "17",
        name: "Click - maps",
        type: "linkClick",
        filter: [
          {
            type: "matchRegex",
            parameter: [
              {
                type: "template",
                key: "arg0",
                value: "{{Click URL}}",
              },
              {
                type: "template",
                key: "arg1",
                value: "maps\\.google\\.|google\\.[a-z.]+/maps|maps\\.app\\.goo\\.gl",
              },
            ],
          },
        ],
        autoEventFilter: [
          {
            type: "matchRegex",
            parameter: [
              {
                type: "template",
                key: "arg0",
                value: "{{Page URL}}",
              },
              {
                type: "template",
                key: "arg1",
                value: ".*",
              },
            ],
          },
        ],
        waitForTags: {
          type: "boolean",
          value: "true",
        },
        checkValidation: {
          type: "boolean",
          value: "false",
        },
        waitForTagsTimeout: {
          type: "template",
          value: "2000",
        },
        uniqueTriggerId: {
          type: "template",
        },
        fingerprint: "1790550118353",
        notes: "Fires on a click of a Google Maps link (a directions request).",
      },
    ],
    tag: [
      {
        accountId: "6004731770",
        containerId: "263680884",
        tagId: "18",
        name: "Google Tag",
        type: "googtag",
        notes:
          'Loads the Google tag on every page. No Conversion Linker tag: a Google tag on every page sets the same first-party click cookies. Google\'s Conversion linker help says "If a container loads a Google tag on every page, it does not also need a conversion linker tag." https://support.google.com/tagmanager/answer/7549390. Add the Google Ads account as a destination of this Google tag in Google Ads or GA4 admin.\n---\n{"recipes":["google_tag"]}',
        parameter: [
          {
            type: "template",
            key: "tagId",
            value: "{{Const - GA4 Measurement ID}}",
          },
        ],
        fingerprint: "1790550123359",
        firingTriggerId: ["2147479573"],
        consentSettings: {
          consentStatus: "notNeeded",
        },
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        tagId: "19",
        name: "GA4 - contact_form_submit",
        type: "gaawe",
        notes:
          'Sends the contact_form_submit event to GA4.\n---\n{"recipes":["contact_form_submit"]}',
        parameter: [
          {
            type: "list",
            key: "eventSettingsTable",
            list: [
              {
                type: "map",
                map: [
                  {
                    type: "template",
                    key: "parameter",
                    value: "form_id",
                  },
                  {
                    type: "template",
                    key: "parameterValue",
                    value: "{{DLV - form_id}}",
                  },
                ],
              },
              {
                type: "map",
                map: [
                  {
                    type: "template",
                    key: "parameter",
                    value: "form_name",
                  },
                  {
                    type: "template",
                    key: "parameterValue",
                    value: "{{DLV - form_name}}",
                  },
                ],
              },
              {
                type: "map",
                map: [
                  {
                    type: "template",
                    key: "parameter",
                    value: "form_destination",
                  },
                  {
                    type: "template",
                    key: "parameterValue",
                    value: "{{DLV - form_destination}}",
                  },
                ],
              },
              {
                type: "map",
                map: [
                  {
                    type: "template",
                    key: "parameter",
                    value: "form_submit_text",
                  },
                  {
                    type: "template",
                    key: "parameterValue",
                    value: "{{DLV - form_submit_text}}",
                  },
                ],
              },
            ],
          },
          {
            type: "template",
            key: "eventName",
            value: "contact_form_submit",
          },
          {
            type: "template",
            key: "measurementIdOverride",
            value: "{{Const - GA4 Measurement ID}}",
          },
        ],
        fingerprint: "1790550128380",
        firingTriggerId: ["14"],
        consentSettings: {
          consentStatus: "notNeeded",
        },
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        tagId: "20",
        name: "Ads - contact_form_submit",
        type: "awct",
        notes:
          'Records the contact_form_submit conversion in Google Ads.\n---\n{"recipes":["contact_form_submit"]}',
        parameter: [
          {
            type: "boolean",
            key: "enableConversionLinker",
            value: "true",
          },
          {
            type: "template",
            key: "conversionId",
            value: "{{Const - Google Ads Conversion ID}}",
          },
          {
            type: "template",
            key: "conversionLabel",
            value: "{{Const - Google Ads - contact_form_submit Conversion Label}}",
          },
        ],
        fingerprint: "1790550133369",
        firingTriggerId: ["14"],
        consentSettings: {
          consentStatus: "notNeeded",
        },
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        tagId: "21",
        name: "GA4 - call_click",
        type: "gaawe",
        notes: 'Sends the call_click event to GA4.\n---\n{"recipes":["call_click"]}',
        parameter: [
          {
            type: "list",
            key: "eventSettingsTable",
            list: [
              {
                type: "map",
                map: [
                  {
                    type: "template",
                    key: "parameter",
                    value: "link_url",
                  },
                  {
                    type: "template",
                    key: "parameterValue",
                    value: "{{Click URL}}",
                  },
                ],
              },
              {
                type: "map",
                map: [
                  {
                    type: "template",
                    key: "parameter",
                    value: "link_text",
                  },
                  {
                    type: "template",
                    key: "parameterValue",
                    value: "{{Click Text}}",
                  },
                ],
              },
            ],
          },
          {
            type: "template",
            key: "eventName",
            value: "call_click",
          },
          {
            type: "template",
            key: "measurementIdOverride",
            value: "{{Const - GA4 Measurement ID}}",
          },
        ],
        fingerprint: "1790550138352",
        firingTriggerId: ["15"],
        consentSettings: {
          consentStatus: "notNeeded",
        },
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        tagId: "22",
        name: "Ads - call_click",
        type: "awct",
        notes: 'Records the call_click conversion in Google Ads.\n---\n{"recipes":["call_click"]}',
        parameter: [
          {
            type: "boolean",
            key: "enableConversionLinker",
            value: "true",
          },
          {
            type: "template",
            key: "conversionId",
            value: "{{Const - Google Ads Conversion ID}}",
          },
          {
            type: "template",
            key: "conversionLabel",
            value: "{{Const - Google Ads - call_click Conversion Label}}",
          },
        ],
        fingerprint: "1790550143376",
        firingTriggerId: ["15"],
        consentSettings: {
          consentStatus: "notNeeded",
        },
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        tagId: "23",
        name: "GA4 - email_click",
        type: "gaawe",
        notes: 'Sends the email_click event to GA4.\n---\n{"recipes":["email_click"]}',
        parameter: [
          {
            type: "list",
            key: "eventSettingsTable",
            list: [
              {
                type: "map",
                map: [
                  {
                    type: "template",
                    key: "parameter",
                    value: "link_url",
                  },
                  {
                    type: "template",
                    key: "parameterValue",
                    value: "{{Click URL}}",
                  },
                ],
              },
              {
                type: "map",
                map: [
                  {
                    type: "template",
                    key: "parameter",
                    value: "link_text",
                  },
                  {
                    type: "template",
                    key: "parameterValue",
                    value: "{{Click Text}}",
                  },
                ],
              },
            ],
          },
          {
            type: "template",
            key: "eventName",
            value: "email_click",
          },
          {
            type: "template",
            key: "measurementIdOverride",
            value: "{{Const - GA4 Measurement ID}}",
          },
        ],
        fingerprint: "1790550148335",
        firingTriggerId: ["16"],
        consentSettings: {
          consentStatus: "notNeeded",
        },
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        tagId: "24",
        name: "Ads - email_click",
        type: "awct",
        notes:
          'Records the email_click conversion in Google Ads.\n---\n{"recipes":["email_click"]}',
        parameter: [
          {
            type: "boolean",
            key: "enableConversionLinker",
            value: "true",
          },
          {
            type: "template",
            key: "conversionId",
            value: "{{Const - Google Ads Conversion ID}}",
          },
          {
            type: "template",
            key: "conversionLabel",
            value: "{{Const - Google Ads - email_click Conversion Label}}",
          },
        ],
        fingerprint: "1790550153376",
        firingTriggerId: ["16"],
        consentSettings: {
          consentStatus: "notNeeded",
        },
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        tagId: "25",
        name: "GA4 - maps_click",
        type: "gaawe",
        notes: 'Sends the maps_click event to GA4.\n---\n{"recipes":["maps_click"]}',
        parameter: [
          {
            type: "list",
            key: "eventSettingsTable",
            list: [
              {
                type: "map",
                map: [
                  {
                    type: "template",
                    key: "parameter",
                    value: "link_url",
                  },
                  {
                    type: "template",
                    key: "parameterValue",
                    value: "{{Click URL}}",
                  },
                ],
              },
              {
                type: "map",
                map: [
                  {
                    type: "template",
                    key: "parameter",
                    value: "link_text",
                  },
                  {
                    type: "template",
                    key: "parameterValue",
                    value: "{{Click Text}}",
                  },
                ],
              },
            ],
          },
          {
            type: "template",
            key: "eventName",
            value: "maps_click",
          },
          {
            type: "template",
            key: "measurementIdOverride",
            value: "{{Const - GA4 Measurement ID}}",
          },
        ],
        fingerprint: "1790550158347",
        firingTriggerId: ["17"],
        consentSettings: {
          consentStatus: "notNeeded",
        },
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        tagId: "26",
        name: "Ads - maps_click",
        type: "awct",
        notes: 'Records the maps_click conversion in Google Ads.\n---\n{"recipes":["maps_click"]}',
        parameter: [
          {
            type: "boolean",
            key: "enableConversionLinker",
            value: "true",
          },
          {
            type: "template",
            key: "conversionId",
            value: "{{Const - Google Ads Conversion ID}}",
          },
          {
            type: "template",
            key: "conversionLabel",
            value: "{{Const - Google Ads - maps_click Conversion Label}}",
          },
        ],
        fingerprint: "1790550163349",
        firingTriggerId: ["17"],
        consentSettings: {
          consentStatus: "notNeeded",
        },
      },
    ],
    builtInVariable: [
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "pageUrl",
        name: "Page URL",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "pageHostname",
        name: "Page Hostname",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "pagePath",
        name: "Page Path",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "referrer",
        name: "Referrer",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "event",
        name: "Event",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "clickElement",
        name: "Click Element",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "clickClasses",
        name: "Click Classes",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "clickId",
        name: "Click ID",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "clickTarget",
        name: "Click Target",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "clickUrl",
        name: "Click URL",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "clickText",
        name: "Click Text",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "formElement",
        name: "Form Element",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "formClasses",
        name: "Form Classes",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "formId",
        name: "Form ID",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "formTarget",
        name: "Form Target",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "formUrl",
        name: "Form URL",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "formText",
        name: "Form Text",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "errorMessage",
        name: "Error Message",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "errorUrl",
        name: "Error URL",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "errorLine",
        name: "Error Line",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "newHistoryFragment",
        name: "New History Fragment",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "oldHistoryFragment",
        name: "Old History Fragment",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "newHistoryState",
        name: "New History State",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "oldHistoryState",
        name: "Old History State",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "historySource",
        name: "History Source",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "containerVersion",
        name: "Container Version",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "debugMode",
        name: "Debug Mode",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "randomNumber",
        name: "Random Number",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "containerId",
        name: "Container ID",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "htmlId",
        name: "HTML ID",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "environmentName",
        name: "Environment Name",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "videoProvider",
        name: "Video Provider",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "videoUrl",
        name: "Video URL",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "videoTitle",
        name: "Video Title",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "videoDuration",
        name: "Video Duration",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "videoPercent",
        name: "Video Percent",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "videoVisible",
        name: "Video Visible",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "videoStatus",
        name: "Video Status",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "videoCurrentTime",
        name: "Video Current Time",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "scrollDepthThreshold",
        name: "Scroll Depth Threshold",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "scrollDepthUnits",
        name: "Scroll Depth Units",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "scrollDepthDirection",
        name: "Scroll Direction",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "elementVisibilityRatio",
        name: "Percent Visible",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "elementVisibilityTime",
        name: "On-Screen Duration",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "analyticsClientId",
        name: "Analytics Client ID",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "analyticsSessionId",
        name: "Analytics Session ID",
      },
      {
        accountId: "6004731770",
        containerId: "263680884",
        type: "analyticsSessionNumber",
        name: "Analytics Session Number",
      },
    ],
    gtagConfig: [],
    customTemplate: [],
    client: [],
    transformation: [],
  },
  manifest: {
    conventions: {},
    recipes: {
      google_tag: {
        description: "Google tag on Initialization; base for every recipe.",
      },
      contact_form_submit: {
        description: "Contact form submitted (dataLayer event).",
        dependencies: [
          {
            constant: "Const - Google Ads - contact_form_submit Conversion Label",
            platform: "googleAds",
            resource: "conversionAction",
          },
        ],
      },
      call_click: {
        description: "tel: link clicked.",
        dependencies: [
          {
            constant: "Const - Google Ads - call_click Conversion Label",
            platform: "googleAds",
            resource: "conversionAction",
          },
        ],
      },
      email_click: {
        description: "mailto: link clicked.",
        dependencies: [
          {
            constant: "Const - Google Ads - email_click Conversion Label",
            platform: "googleAds",
            resource: "conversionAction",
          },
        ],
      },
      maps_click: {
        description: "Google Maps link clicked.",
        dependencies: [
          {
            constant: "Const - Google Ads - maps_click Conversion Label",
            platform: "googleAds",
            resource: "conversionAction",
          },
        ],
      },
    },
  },
  encoding: {
    name: "notes",
  },
  metadata: {
    "variable:Const - GA4 Measurement ID": {
      placeholder: {
        kind: "ga4MeasurementId",
        example: "G-ABC123DEF4",
        pattern: "^G-[A-Z0-9]+$",
      },
    },
    "variable:Const - Google Ads Conversion ID": {
      placeholder: {
        kind: "adsConversionId",
        example: "123456789",
        pattern: "^[0-9]+$",
      },
    },
    "variable:Const - Google Ads - contact_form_submit Conversion Label": {
      placeholder: {
        kind: "adsConversionLabel",
        example: "AbCdEfGhIjKlMnOp",
        pattern: "^[A-Za-z0-9_-]{5,}$",
      },
    },
    "variable:Const - Google Ads - call_click Conversion Label": {
      placeholder: {
        kind: "adsConversionLabel",
        example: "AbCdEfGhIjKlMnOp",
        pattern: "^[A-Za-z0-9_-]{5,}$",
      },
    },
    "variable:Const - Google Ads - email_click Conversion Label": {
      placeholder: {
        kind: "adsConversionLabel",
        example: "AbCdEfGhIjKlMnOp",
        pattern: "^[A-Za-z0-9_-]{5,}$",
      },
    },
    "variable:Const - Google Ads - maps_click Conversion Label": {
      placeholder: {
        kind: "adsConversionLabel",
        example: "AbCdEfGhIjKlMnOp",
        pattern: "^[A-Za-z0-9_-]{5,}$",
      },
    },
    "tag:Google Tag": {
      recipes: ["google_tag"],
    },
    "tag:GA4 - contact_form_submit": {
      recipes: ["contact_form_submit"],
    },
    "tag:Ads - contact_form_submit": {
      recipes: ["contact_form_submit"],
    },
    "tag:GA4 - call_click": {
      recipes: ["call_click"],
    },
    "tag:Ads - call_click": {
      recipes: ["call_click"],
    },
    "tag:GA4 - email_click": {
      recipes: ["email_click"],
    },
    "tag:Ads - email_click": {
      recipes: ["email_click"],
    },
    "tag:GA4 - maps_click": {
      recipes: ["maps_click"],
    },
    "tag:Ads - maps_click": {
      recipes: ["maps_click"],
    },
  },
  recipes: [
    {
      name: "google_tag",
      description: "Google tag on Initialization; base for every recipe.",
      roots: [
        {
          kind: "tag",
          name: "Google Tag",
        },
      ],
      entities: [
        {
          kind: "tag",
          name: "Google Tag",
        },
        {
          kind: "trigger",
          name: "Initialization - All Pages",
        },
        {
          kind: "variable",
          name: "Const - GA4 Measurement ID",
        },
      ],
      dependencies: [],
    },
    {
      name: "contact_form_submit",
      description: "Contact form submitted (dataLayer event).",
      roots: [
        {
          kind: "tag",
          name: "GA4 - contact_form_submit",
        },
        {
          kind: "tag",
          name: "Ads - contact_form_submit",
        },
      ],
      entities: [
        {
          kind: "tag",
          name: "GA4 - contact_form_submit",
        },
        {
          kind: "tag",
          name: "Ads - contact_form_submit",
        },
        {
          kind: "trigger",
          name: "Custom Event - contact_form_submit",
        },
        {
          kind: "variable",
          name: "DLV - form_id",
        },
        {
          kind: "variable",
          name: "DLV - form_name",
        },
        {
          kind: "variable",
          name: "DLV - form_destination",
        },
        {
          kind: "variable",
          name: "DLV - form_submit_text",
        },
        {
          kind: "variable",
          name: "Const - GA4 Measurement ID",
        },
        {
          kind: "variable",
          name: "Const - Google Ads Conversion ID",
        },
        {
          kind: "variable",
          name: "Const - Google Ads - contact_form_submit Conversion Label",
        },
      ],
      dependencies: [
        {
          constant: "Const - Google Ads - contact_form_submit Conversion Label",
          platform: "googleAds",
          resource: "conversionAction",
        },
      ],
    },
    {
      name: "call_click",
      description: "tel: link clicked.",
      roots: [
        {
          kind: "tag",
          name: "GA4 - call_click",
        },
        {
          kind: "tag",
          name: "Ads - call_click",
        },
      ],
      entities: [
        {
          kind: "tag",
          name: "GA4 - call_click",
        },
        {
          kind: "tag",
          name: "Ads - call_click",
        },
        {
          kind: "trigger",
          name: "Click - call",
        },
        {
          kind: "builtInVariable",
          name: "clickUrl",
        },
        {
          kind: "builtInVariable",
          name: "clickText",
        },
        {
          kind: "variable",
          name: "Const - GA4 Measurement ID",
        },
        {
          kind: "variable",
          name: "Const - Google Ads Conversion ID",
        },
        {
          kind: "variable",
          name: "Const - Google Ads - call_click Conversion Label",
        },
        {
          kind: "builtInVariable",
          name: "pageUrl",
        },
      ],
      dependencies: [
        {
          constant: "Const - Google Ads - call_click Conversion Label",
          platform: "googleAds",
          resource: "conversionAction",
        },
      ],
    },
    {
      name: "email_click",
      description: "mailto: link clicked.",
      roots: [
        {
          kind: "tag",
          name: "GA4 - email_click",
        },
        {
          kind: "tag",
          name: "Ads - email_click",
        },
      ],
      entities: [
        {
          kind: "tag",
          name: "GA4 - email_click",
        },
        {
          kind: "tag",
          name: "Ads - email_click",
        },
        {
          kind: "trigger",
          name: "Click - email",
        },
        {
          kind: "builtInVariable",
          name: "clickUrl",
        },
        {
          kind: "builtInVariable",
          name: "clickText",
        },
        {
          kind: "variable",
          name: "Const - GA4 Measurement ID",
        },
        {
          kind: "variable",
          name: "Const - Google Ads Conversion ID",
        },
        {
          kind: "variable",
          name: "Const - Google Ads - email_click Conversion Label",
        },
        {
          kind: "builtInVariable",
          name: "pageUrl",
        },
      ],
      dependencies: [
        {
          constant: "Const - Google Ads - email_click Conversion Label",
          platform: "googleAds",
          resource: "conversionAction",
        },
      ],
    },
    {
      name: "maps_click",
      description: "Google Maps link clicked.",
      roots: [
        {
          kind: "tag",
          name: "GA4 - maps_click",
        },
        {
          kind: "tag",
          name: "Ads - maps_click",
        },
      ],
      entities: [
        {
          kind: "tag",
          name: "GA4 - maps_click",
        },
        {
          kind: "tag",
          name: "Ads - maps_click",
        },
        {
          kind: "trigger",
          name: "Click - maps",
        },
        {
          kind: "builtInVariable",
          name: "clickUrl",
        },
        {
          kind: "builtInVariable",
          name: "clickText",
        },
        {
          kind: "variable",
          name: "Const - GA4 Measurement ID",
        },
        {
          kind: "variable",
          name: "Const - Google Ads Conversion ID",
        },
        {
          kind: "variable",
          name: "Const - Google Ads - maps_click Conversion Label",
        },
        {
          kind: "builtInVariable",
          name: "pageUrl",
        },
      ],
      dependencies: [
        {
          constant: "Const - Google Ads - maps_click Conversion Label",
          platform: "googleAds",
          resource: "conversionAction",
        },
      ],
    },
  ],
} as const;
