// GENERATED by gtm-apply from a Tag Manager container. Do not edit; run the package's pull script.
export const data = {
  pulledAt: "1970-01-01T00:00:00.000Z",
  source: {
    container: "GTM-SAMPLE",
  },
  container: {
    accountId: "1",
    containerId: "10",
    publicId: "GTM-SAMPLE",
    name: "Web Template (sample)",
    usageContext: ["web"],
    path: "accounts/1/containers/10",
  },
  containerType: "web",
  workspace: null,
  containerVersionHeader: {
    containerVersionId: "18",
    path: "accounts/1/containers/10/versions/18",
    name: "sample",
    numTags: "7",
    numClients: "0",
  },
  environments: [],
  environment: null,
  destinations: [],
  folder: [],
  variable: [
    {
      name: "Library - Manifest",
      type: "c",
      parameter: [
        {
          type: "template",
          key: "value",
          value:
            '{"encoding":{"name":"metadata"},"conventions":{},"recipes":{"form_submit":{"description":"A lead form was submitted (dataLayer event form_submit)","dependencies":[{"constant":"Const - Ads Label - form_submit","platform":"googleAds","resource":"conversionAction","pattern":"^[A-Za-z0-9_-]{5,}$"}]},"email_click":{"description":"A mailto: link was clicked","dependencies":[{"constant":"Const - Ads Label - email_click","platform":"googleAds","resource":"conversionAction","pattern":"^[A-Za-z0-9_-]{5,}$"}]},"call_click":{"description":"A tel: link was clicked","dependencies":[{"constant":"Const - Ads Label - call_click","platform":"googleAds","resource":"conversionAction","pattern":"^[A-Za-z0-9_-]{5,}$"}]}}}',
        },
      ],
      variableId: "2",
      path: "accounts/1/containers/10/workspace/1/variable/2",
      fingerprint: "1",
    },
    {
      name: "Const - GA4 Measurement ID",
      type: "c",
      parameter: [
        {
          type: "template",
          key: "value",
          value: "<G-XXXXXXX>",
        },
      ],
      variableId: "3",
      path: "accounts/1/containers/10/workspace/1/variable/3",
      fingerprint: "1",
    },
    {
      name: "Const - Ads Conversion ID",
      type: "c",
      parameter: [
        {
          type: "template",
          key: "value",
          value: "<AW-XXXXXXXXX>",
        },
      ],
      variableId: "4",
      path: "accounts/1/containers/10/workspace/1/variable/4",
      fingerprint: "1",
    },
    {
      name: "Const - Ads Label - form_submit",
      type: "c",
      parameter: [
        {
          type: "template",
          key: "value",
          value: "<label>",
        },
      ],
      variableId: "5",
      path: "accounts/1/containers/10/workspace/1/variable/5",
      fingerprint: "1",
    },
    {
      name: "Const - Ads Label - email_click",
      type: "c",
      parameter: [
        {
          type: "template",
          key: "value",
          value: "<label>",
        },
      ],
      variableId: "6",
      path: "accounts/1/containers/10/workspace/1/variable/6",
      fingerprint: "1",
    },
    {
      name: "Const - Ads Label - call_click",
      type: "c",
      parameter: [
        {
          type: "template",
          key: "value",
          value: "<label>",
        },
      ],
      variableId: "7",
      path: "accounts/1/containers/10/workspace/1/variable/7",
      fingerprint: "1",
    },
  ],
  trigger: [
    {
      name: "Custom Event - form_submit",
      type: "customEvent",
      customEventFilter: [
        {
          type: "equals",
          parameter: [
            {
              type: "template",
              key: "arg0",
              value: "{{_event}}",
            },
            {
              type: "template",
              key: "arg1",
              value: "form_submit",
            },
          ],
        },
      ],
      triggerId: "8",
      path: "accounts/1/containers/10/workspace/1/trigger/8",
      fingerprint: "1",
    },
    {
      name: "Click - email",
      type: "linkClick",
      filter: [
        {
          type: "startsWith",
          parameter: [
            {
              type: "template",
              key: "arg0",
              value: "{{Click URL}}",
            },
            {
              type: "template",
              key: "arg1",
              value: "mailto:",
            },
          ],
        },
      ],
      triggerId: "9",
      path: "accounts/1/containers/10/workspace/1/trigger/9",
      fingerprint: "1",
    },
    {
      name: "Click - call",
      type: "linkClick",
      filter: [
        {
          type: "startsWith",
          parameter: [
            {
              type: "template",
              key: "arg0",
              value: "{{Click URL}}",
            },
            {
              type: "template",
              key: "arg1",
              value: "tel:",
            },
          ],
        },
      ],
      triggerId: "10",
      path: "accounts/1/containers/10/workspace/1/trigger/10",
      fingerprint: "1",
    },
  ],
  tag: [
    {
      name: "GA4 - form_submit",
      type: "gaawe",
      monitoringMetadata: {
        type: "map",
        map: [
          {
            type: "template",
            key: "recipes",
            value: "form_submit",
          },
        ],
      },
      parameter: [
        {
          type: "template",
          key: "eventName",
          value: "form_submit",
        },
        {
          type: "template",
          key: "measurementIdOverride",
          value: "{{Const - GA4 Measurement ID}}",
        },
      ],
      firingTriggerId: ["8"],
      tagId: "11",
      path: "accounts/1/containers/10/workspace/1/tag/11",
      fingerprint: "1",
    },
    {
      name: "Ads - form_submit",
      type: "awct",
      monitoringMetadata: {
        type: "map",
        map: [
          {
            type: "template",
            key: "recipes",
            value: "form_submit",
          },
        ],
      },
      setupTag: [
        {
          tagName: "Conversion Linker",
        },
      ],
      parameter: [
        {
          type: "template",
          key: "conversionId",
          value: "{{Const - Ads Conversion ID}}",
        },
        {
          type: "template",
          key: "conversionLabel",
          value: "{{Const - Ads Label - form_submit}}",
        },
      ],
      firingTriggerId: ["8"],
      tagId: "12",
      path: "accounts/1/containers/10/workspace/1/tag/12",
      fingerprint: "1",
    },
    {
      name: "GA4 - email_click",
      type: "gaawe",
      monitoringMetadata: {
        type: "map",
        map: [
          {
            type: "template",
            key: "recipes",
            value: "email_click",
          },
        ],
      },
      parameter: [
        {
          type: "template",
          key: "eventName",
          value: "email_click",
        },
        {
          type: "template",
          key: "measurementIdOverride",
          value: "{{Const - GA4 Measurement ID}}",
        },
      ],
      firingTriggerId: ["9"],
      tagId: "13",
      path: "accounts/1/containers/10/workspace/1/tag/13",
      fingerprint: "1",
    },
    {
      name: "Ads - email_click",
      type: "awct",
      monitoringMetadata: {
        type: "map",
        map: [
          {
            type: "template",
            key: "recipes",
            value: "email_click",
          },
        ],
      },
      setupTag: [
        {
          tagName: "Conversion Linker",
        },
      ],
      parameter: [
        {
          type: "template",
          key: "conversionId",
          value: "{{Const - Ads Conversion ID}}",
        },
        {
          type: "template",
          key: "conversionLabel",
          value: "{{Const - Ads Label - email_click}}",
        },
      ],
      firingTriggerId: ["9"],
      tagId: "14",
      path: "accounts/1/containers/10/workspace/1/tag/14",
      fingerprint: "1",
    },
    {
      name: "GA4 - call_click",
      type: "gaawe",
      monitoringMetadata: {
        type: "map",
        map: [
          {
            type: "template",
            key: "recipes",
            value: "call_click",
          },
        ],
      },
      parameter: [
        {
          type: "template",
          key: "eventName",
          value: "call_click",
        },
        {
          type: "template",
          key: "measurementIdOverride",
          value: "{{Const - GA4 Measurement ID}}",
        },
      ],
      firingTriggerId: ["10"],
      tagId: "15",
      path: "accounts/1/containers/10/workspace/1/tag/15",
      fingerprint: "1",
    },
    {
      name: "Ads - call_click",
      type: "awct",
      monitoringMetadata: {
        type: "map",
        map: [
          {
            type: "template",
            key: "recipes",
            value: "call_click",
          },
        ],
      },
      setupTag: [
        {
          tagName: "Conversion Linker",
        },
      ],
      parameter: [
        {
          type: "template",
          key: "conversionId",
          value: "{{Const - Ads Conversion ID}}",
        },
        {
          type: "template",
          key: "conversionLabel",
          value: "{{Const - Ads Label - call_click}}",
        },
      ],
      firingTriggerId: ["10"],
      tagId: "16",
      path: "accounts/1/containers/10/workspace/1/tag/16",
      fingerprint: "1",
    },
    {
      name: "Conversion Linker",
      type: "gclidw",
      monitoringMetadata: {
        type: "map",
        map: [
          {
            type: "template",
            key: "recipes",
            value: "form_submit, email_click, call_click",
          },
        ],
      },
      tagId: "17",
      path: "accounts/1/containers/10/workspace/1/tag/17",
      fingerprint: "1",
    },
  ],
  builtInVariable: [
    {
      type: "clickUrl",
    },
  ],
  gtagConfig: [],
  customTemplate: [],
  client: [],
  transformation: [],
  zone: [],
  manifest: {
    encoding: {
      name: "metadata",
    },
    conventions: {},
    recipes: {
      form_submit: {
        description: "A lead form was submitted (dataLayer event form_submit)",
        dependencies: [
          {
            constant: "Const - Ads Label - form_submit",
            platform: "googleAds",
            resource: "conversionAction",
            pattern: "^[A-Za-z0-9_-]{5,}$",
          },
        ],
      },
      email_click: {
        description: "A mailto: link was clicked",
        dependencies: [
          {
            constant: "Const - Ads Label - email_click",
            platform: "googleAds",
            resource: "conversionAction",
            pattern: "^[A-Za-z0-9_-]{5,}$",
          },
        ],
      },
      call_click: {
        description: "A tel: link was clicked",
        dependencies: [
          {
            constant: "Const - Ads Label - call_click",
            platform: "googleAds",
            resource: "conversionAction",
            pattern: "^[A-Za-z0-9_-]{5,}$",
          },
        ],
      },
    },
  },
  encoding: {
    name: "metadata",
  },
  recipes: [
    {
      name: "form_submit",
      description: "A lead form was submitted (dataLayer event form_submit)",
      roots: [
        {
          kind: "tag",
          name: "GA4 - form_submit",
        },
        {
          kind: "tag",
          name: "Ads - form_submit",
        },
        {
          kind: "tag",
          name: "Conversion Linker",
        },
      ],
      entities: [
        {
          kind: "tag",
          name: "GA4 - form_submit",
        },
        {
          kind: "tag",
          name: "Ads - form_submit",
        },
        {
          kind: "tag",
          name: "Conversion Linker",
        },
        {
          kind: "trigger",
          name: "Custom Event - form_submit",
        },
        {
          kind: "variable",
          name: "Const - GA4 Measurement ID",
        },
        {
          kind: "variable",
          name: "Const - Ads Conversion ID",
        },
        {
          kind: "variable",
          name: "Const - Ads Label - form_submit",
        },
      ],
      dependencies: [
        {
          constant: "Const - Ads Label - form_submit",
          platform: "googleAds",
          resource: "conversionAction",
          pattern: "^[A-Za-z0-9_-]{5,}$",
        },
      ],
    },
    {
      name: "email_click",
      description: "A mailto: link was clicked",
      roots: [
        {
          kind: "tag",
          name: "GA4 - email_click",
        },
        {
          kind: "tag",
          name: "Ads - email_click",
        },
        {
          kind: "tag",
          name: "Conversion Linker",
        },
      ],
      entities: [
        {
          kind: "tag",
          name: "GA4 - email_click",
        },
        {
          kind: "tag",
          name: "Ads - email_click",
        },
        {
          kind: "tag",
          name: "Conversion Linker",
        },
        {
          kind: "trigger",
          name: "Click - email",
        },
        {
          kind: "variable",
          name: "Const - GA4 Measurement ID",
        },
        {
          kind: "variable",
          name: "Const - Ads Conversion ID",
        },
        {
          kind: "variable",
          name: "Const - Ads Label - email_click",
        },
        {
          kind: "builtInVariable",
          name: "clickUrl",
        },
      ],
      dependencies: [
        {
          constant: "Const - Ads Label - email_click",
          platform: "googleAds",
          resource: "conversionAction",
          pattern: "^[A-Za-z0-9_-]{5,}$",
        },
      ],
    },
    {
      name: "call_click",
      description: "A tel: link was clicked",
      roots: [
        {
          kind: "tag",
          name: "GA4 - call_click",
        },
        {
          kind: "tag",
          name: "Ads - call_click",
        },
        {
          kind: "tag",
          name: "Conversion Linker",
        },
      ],
      entities: [
        {
          kind: "tag",
          name: "GA4 - call_click",
        },
        {
          kind: "tag",
          name: "Ads - call_click",
        },
        {
          kind: "tag",
          name: "Conversion Linker",
        },
        {
          kind: "trigger",
          name: "Click - call",
        },
        {
          kind: "variable",
          name: "Const - GA4 Measurement ID",
        },
        {
          kind: "variable",
          name: "Const - Ads Conversion ID",
        },
        {
          kind: "variable",
          name: "Const - Ads Label - call_click",
        },
        {
          kind: "builtInVariable",
          name: "clickUrl",
        },
      ],
      dependencies: [
        {
          constant: "Const - Ads Label - call_click",
          platform: "googleAds",
          resource: "conversionAction",
          pattern: "^[A-Za-z0-9_-]{5,}$",
        },
      ],
    },
  ],
} as const;
