// GENERATED by gtm-apply from a Tag Manager container. Do not edit; run the package's pull script.
export const data = {
  data: {
    pulledAt: "2026-09-29T00:08:29.768Z",
    source: {
      container: "GTM-WMGVDZ5H",
    },
    container: {
      path: "accounts/6004731770/containers/265489931",
      accountId: "6004731770",
      containerId: "265489931",
      name: "Template - Server",
      publicId: "GTM-WMGVDZ5H",
      usageContext: ["server"],
      fingerprint: "1790626866961",
      tagManagerUrl:
        "https://tagmanager.google.com/#/container/accounts/6004731770/containers/265489931/workspaces?apiLink=container",
      features: {
        supportUserPermissions: true,
        supportEnvironments: true,
        supportWorkspaces: true,
        supportGtagConfigs: false,
        supportBuiltInVariables: true,
        supportClients: true,
        supportFolders: true,
        supportTags: true,
        supportTemplates: true,
        supportTriggers: true,
        supportVariables: true,
        supportVersions: true,
        supportZones: true,
        supportTransformations: true,
      },
      tagIds: ["GTM-WMGVDZ5H"],
    },
    containerType: "server",
    environments: [
      {
        path: "accounts/6004731770/containers/265489931/environments/2",
        accountId: "6004731770",
        containerId: "265489931",
        environmentId: "2",
        type: "live",
        fingerprint: "1790626867023",
        name: "Live",
        description: "This environment points to the currently published version.",
        authorizationCode: "BwHr4KIZ2IGdy52MZQYihg",
        authorizationTimestamp: "2026-09-28T20:21:07.023Z",
        tagManagerUrl:
          "https://tagmanager.google.com/#/admin/accounts/6004731770/containers/265489931/environments?apiLink=environment",
      },
      {
        path: "accounts/6004731770/containers/265489931/environments/3",
        accountId: "6004731770",
        containerId: "265489931",
        environmentId: "3",
        type: "latest",
        fingerprint: "1790626867023",
        name: "Latest",
        description: "This environment points to the latest created version.",
        authorizationCode: "4_oIsAJrSCkvpsEjBGB7gg",
        authorizationTimestamp: "2026-09-28T20:21:07.023Z",
        tagManagerUrl:
          "https://tagmanager.google.com/#/admin/accounts/6004731770/containers/265489931/environments?apiLink=environment",
      },
    ],
    destinations: [],
    workspace: null,
    containerVersionHeader: {
      path: "accounts/6004731770/containers/265489931/versions/4",
      accountId: "6004731770",
      containerId: "265489931",
      containerVersionId: "4",
      name: "recipes-2026-09-29-copy",
      numTags: "6",
      numTriggers: "5",
      numVariables: "7",
      numClients: "2",
    },
    environment: null,
    folder: [],
    variable: [
      {
        accountId: "6004731770",
        containerId: "265489931",
        variableId: "5",
        name: "Library - Manifest",
        type: "c",
        parameter: [
          {
            type: "template",
            key: "value",
            value:
              '{"conventions":{},"recipes":{"ga4_client":{"description":"GA4 client, GA4 forwarding, Conversion Linker; base for every recipe."},"contact_form_submit":{"description":"Contact form submitted.","dependencies":[{"constant":"Const - Google Ads - contact_form_submit Conversion Label","platform":"googleAds","resource":"conversionAction"}]},"call_click":{"description":"tel: link clicked.","dependencies":[{"constant":"Const - Google Ads - call_click Conversion Label","platform":"googleAds","resource":"conversionAction"}]},"email_click":{"description":"mailto: link clicked.","dependencies":[{"constant":"Const - Google Ads - email_click Conversion Label","platform":"googleAds","resource":"conversionAction"}]},"maps_click":{"description":"Google Maps link clicked.","dependencies":[{"constant":"Const - Google Ads - maps_click Conversion Label","platform":"googleAds","resource":"conversionAction"}]},"web_container_client":{"description":"Serves the web container\'s gtm.js first-party."}}}',
          },
        ],
        fingerprint: "1790640058605",
      },
      {
        accountId: "6004731770",
        containerId: "265489931",
        variableId: "6",
        name: "Const - Google Ads Conversion ID",
        type: "c",
        notes:
          'The bare numeric conversion id (the digits after AW- in Google Ads). GTM stores it without the prefix; the conversion tag builds AW-<id>/<label> itself.\n---\n{"placeholder":{"kind":"adsConversionId","example":"123456789","pattern":"^[0-9]+$"}}',
        parameter: [
          {
            type: "template",
            key: "value",
            value: "<XXXXXXXXX>",
          },
        ],
        fingerprint: "1790640063617",
      },
      {
        accountId: "6004731770",
        containerId: "265489931",
        variableId: "7",
        name: "Const - Google Ads - contact_form_submit Conversion Label",
        type: "c",
        notes:
          'Conversion label of the Google Ads conversion action for contact_form_submit.\n---\n{"placeholder":{"kind":"adsConversionLabel","example":"AbCdEfGhIjKlMnOp","pattern":"^[A-Za-z0-9_-]{5,}$"}}',
        parameter: [
          {
            type: "template",
            key: "value",
            value: "<label>",
          },
        ],
        fingerprint: "1790640068601",
      },
      {
        accountId: "6004731770",
        containerId: "265489931",
        variableId: "8",
        name: "Const - Google Ads - call_click Conversion Label",
        type: "c",
        notes:
          'Conversion label of the Google Ads conversion action for call_click.\n---\n{"placeholder":{"kind":"adsConversionLabel","example":"AbCdEfGhIjKlMnOp","pattern":"^[A-Za-z0-9_-]{5,}$"}}',
        parameter: [
          {
            type: "template",
            key: "value",
            value: "<label>",
          },
        ],
        fingerprint: "1790640073561",
      },
      {
        accountId: "6004731770",
        containerId: "265489931",
        variableId: "9",
        name: "Const - Google Ads - email_click Conversion Label",
        type: "c",
        notes:
          'Conversion label of the Google Ads conversion action for email_click.\n---\n{"placeholder":{"kind":"adsConversionLabel","example":"AbCdEfGhIjKlMnOp","pattern":"^[A-Za-z0-9_-]{5,}$"}}',
        parameter: [
          {
            type: "template",
            key: "value",
            value: "<label>",
          },
        ],
        fingerprint: "1790640078610",
      },
      {
        accountId: "6004731770",
        containerId: "265489931",
        variableId: "10",
        name: "Const - Google Ads - maps_click Conversion Label",
        type: "c",
        notes:
          'Conversion label of the Google Ads conversion action for maps_click.\n---\n{"placeholder":{"kind":"adsConversionLabel","example":"AbCdEfGhIjKlMnOp","pattern":"^[A-Za-z0-9_-]{5,}$"}}',
        parameter: [
          {
            type: "template",
            key: "value",
            value: "<label>",
          },
        ],
        fingerprint: "1790640083566",
      },
      {
        accountId: "6004731770",
        containerId: "265489931",
        variableId: "11",
        name: "Const - Web Container ID",
        type: "c",
        notes:
          'Public id of the web container this tagging server serves.\n---\n{"placeholder":{"kind":"gtmPublicId","example":"GTM-ABC1234","pattern":"^GTM-[A-Z0-9]+$"}}',
        parameter: [
          {
            type: "template",
            key: "value",
            value: "<GTM-XXXXXXX>",
          },
        ],
        fingerprint: "1790640088560",
      },
    ],
    trigger: [
      {
        accountId: "6004731770",
        containerId: "265489931",
        triggerId: "13",
        name: "Client - GA4",
        type: "always",
        filter: [
          {
            type: "equals",
            parameter: [
              {
                type: "template",
                key: "arg0",
                value: "{{Client Name}}",
              },
              {
                type: "template",
                key: "arg1",
                value: "GA4",
              },
            ],
          },
        ],
        fingerprint: "1790640103598",
        notes: "Fires for every event the GA4 client claims.",
      },
      {
        accountId: "6004731770",
        containerId: "265489931",
        triggerId: "14",
        name: "Custom Event - contact_form_submit",
        type: "customEvent",
        customEventFilter: [
          {
            type: "equals",
            parameter: [
              {
                type: "template",
                key: "arg0",
                value: "{{_event}}",
              },
              {
                type: "template",
                key: "arg1",
                value: "contact_form_submit",
              },
            ],
          },
        ],
        filter: [
          {
            type: "equals",
            parameter: [
              {
                type: "template",
                key: "arg0",
                value: "{{Client Name}}",
              },
              {
                type: "template",
                key: "arg1",
                value: "GA4",
              },
            ],
          },
        ],
        fingerprint: "1790640108610",
        notes:
          "Fires when the GA4 client claims the contact_form_submit event sent by the web container.",
      },
      {
        accountId: "6004731770",
        containerId: "265489931",
        triggerId: "15",
        name: "Custom Event - call_click",
        type: "customEvent",
        customEventFilter: [
          {
            type: "equals",
            parameter: [
              {
                type: "template",
                key: "arg0",
                value: "{{_event}}",
              },
              {
                type: "template",
                key: "arg1",
                value: "call_click",
              },
            ],
          },
        ],
        filter: [
          {
            type: "equals",
            parameter: [
              {
                type: "template",
                key: "arg0",
                value: "{{Client Name}}",
              },
              {
                type: "template",
                key: "arg1",
                value: "GA4",
              },
            ],
          },
        ],
        fingerprint: "1790640113566",
        notes: "Fires when the GA4 client claims the call_click event sent by the web container.",
      },
      {
        accountId: "6004731770",
        containerId: "265489931",
        triggerId: "16",
        name: "Custom Event - email_click",
        type: "customEvent",
        customEventFilter: [
          {
            type: "equals",
            parameter: [
              {
                type: "template",
                key: "arg0",
                value: "{{_event}}",
              },
              {
                type: "template",
                key: "arg1",
                value: "email_click",
              },
            ],
          },
        ],
        filter: [
          {
            type: "equals",
            parameter: [
              {
                type: "template",
                key: "arg0",
                value: "{{Client Name}}",
              },
              {
                type: "template",
                key: "arg1",
                value: "GA4",
              },
            ],
          },
        ],
        fingerprint: "1790640118578",
        notes: "Fires when the GA4 client claims the email_click event sent by the web container.",
      },
      {
        accountId: "6004731770",
        containerId: "265489931",
        triggerId: "17",
        name: "Custom Event - maps_click",
        type: "customEvent",
        customEventFilter: [
          {
            type: "equals",
            parameter: [
              {
                type: "template",
                key: "arg0",
                value: "{{_event}}",
              },
              {
                type: "template",
                key: "arg1",
                value: "maps_click",
              },
            ],
          },
        ],
        filter: [
          {
            type: "equals",
            parameter: [
              {
                type: "template",
                key: "arg0",
                value: "{{Client Name}}",
              },
              {
                type: "template",
                key: "arg1",
                value: "GA4",
              },
            ],
          },
        ],
        fingerprint: "1790640123583",
        notes: "Fires when the GA4 client claims the maps_click event sent by the web container.",
      },
    ],
    tag: [
      {
        accountId: "6004731770",
        containerId: "265489931",
        tagId: "18",
        name: "GA4 - All Events",
        type: "sgtmgaaw",
        notes:
          'Forwards every event the GA4 client claims to GA4. Its fields stay at their defaults, so it inherits the measurement id and parameters from each event (https://developers.google.com/tag-platform/learn/sst-fundamentals/5-sst-setup-analytics).\n---\n{"recipes":["ga4_client"]}',
        parameter: [
          {
            type: "template",
            key: "epToIncludeDropdown",
            value: "all",
          },
          {
            type: "boolean",
            key: "redactVisitorIp",
            value: "false",
          },
          {
            type: "boolean",
            key: "isMeasurementIdMandatory",
            value: "false",
          },
          {
            type: "template",
            key: "upToIncludeDropdown",
            value: "all",
          },
        ],
        fingerprint: "1790640128641",
        firingTriggerId: ["13"],
        consentSettings: {
          consentStatus: "notSet",
        },
      },
      {
        accountId: "6004731770",
        containerId: "265489931",
        tagId: "19",
        name: "Conversion Linker",
        type: "sgtmadscl",
        notes:
          'Sets the Google Ads click cookies from the tagging server.\n---\n{"recipes":["ga4_client"]}',
        parameter: [
          {
            type: "boolean",
            key: "enableLinkerParams",
            value: "false",
          },
          {
            type: "boolean",
            key: "enableCookieOverrides",
            value: "false",
          },
        ],
        fingerprint: "1790640133597",
        firingTriggerId: ["2147479574"],
        consentSettings: {
          consentStatus: "notSet",
        },
      },
      {
        accountId: "6004731770",
        containerId: "265489931",
        tagId: "20",
        name: "Ads - contact_form_submit",
        type: "sgtmadsct",
        notes:
          'Records the contact_form_submit conversion in Google Ads from the tagging server.\n---\n{"recipes":["contact_form_submit"]}',
        parameter: [
          {
            type: "boolean",
            key: "enableNewCustomerReporting",
            value: "false",
          },
          {
            type: "boolean",
            key: "enableConversionLinker",
            value: "true",
          },
          {
            type: "boolean",
            key: "enableProductReporting",
            value: "false",
          },
          {
            type: "template",
            key: "conversionId",
            value: "{{Const - Google Ads Conversion ID}}",
          },
          {
            type: "template",
            key: "conversionLabel",
            value: "{{Const - Google Ads - contact_form_submit Conversion Label}}",
          },
          {
            type: "boolean",
            key: "rdp",
            value: "false",
          },
        ],
        fingerprint: "1790640138615",
        firingTriggerId: ["14"],
        consentSettings: {
          consentStatus: "notSet",
        },
      },
      {
        accountId: "6004731770",
        containerId: "265489931",
        tagId: "21",
        name: "Ads - call_click",
        type: "sgtmadsct",
        notes:
          'Records the call_click conversion in Google Ads from the tagging server.\n---\n{"recipes":["call_click"]}',
        parameter: [
          {
            type: "boolean",
            key: "enableNewCustomerReporting",
            value: "false",
          },
          {
            type: "boolean",
            key: "enableConversionLinker",
            value: "true",
          },
          {
            type: "boolean",
            key: "enableProductReporting",
            value: "false",
          },
          {
            type: "template",
            key: "conversionId",
            value: "{{Const - Google Ads Conversion ID}}",
          },
          {
            type: "template",
            key: "conversionLabel",
            value: "{{Const - Google Ads - call_click Conversion Label}}",
          },
          {
            type: "boolean",
            key: "rdp",
            value: "false",
          },
        ],
        fingerprint: "1790640143605",
        firingTriggerId: ["15"],
        consentSettings: {
          consentStatus: "notSet",
        },
      },
      {
        accountId: "6004731770",
        containerId: "265489931",
        tagId: "22",
        name: "Ads - email_click",
        type: "sgtmadsct",
        notes:
          'Records the email_click conversion in Google Ads from the tagging server.\n---\n{"recipes":["email_click"]}',
        parameter: [
          {
            type: "boolean",
            key: "enableNewCustomerReporting",
            value: "false",
          },
          {
            type: "boolean",
            key: "enableConversionLinker",
            value: "true",
          },
          {
            type: "boolean",
            key: "enableProductReporting",
            value: "false",
          },
          {
            type: "template",
            key: "conversionId",
            value: "{{Const - Google Ads Conversion ID}}",
          },
          {
            type: "template",
            key: "conversionLabel",
            value: "{{Const - Google Ads - email_click Conversion Label}}",
          },
          {
            type: "boolean",
            key: "rdp",
            value: "false",
          },
        ],
        fingerprint: "1790640148602",
        firingTriggerId: ["16"],
        consentSettings: {
          consentStatus: "notSet",
        },
      },
      {
        accountId: "6004731770",
        containerId: "265489931",
        tagId: "23",
        name: "Ads - maps_click",
        type: "sgtmadsct",
        notes:
          'Records the maps_click conversion in Google Ads from the tagging server.\n---\n{"recipes":["maps_click"]}',
        parameter: [
          {
            type: "boolean",
            key: "enableNewCustomerReporting",
            value: "false",
          },
          {
            type: "boolean",
            key: "enableConversionLinker",
            value: "true",
          },
          {
            type: "boolean",
            key: "enableProductReporting",
            value: "false",
          },
          {
            type: "template",
            key: "conversionId",
            value: "{{Const - Google Ads Conversion ID}}",
          },
          {
            type: "template",
            key: "conversionLabel",
            value: "{{Const - Google Ads - maps_click Conversion Label}}",
          },
          {
            type: "boolean",
            key: "rdp",
            value: "false",
          },
        ],
        fingerprint: "1790640153627",
        firingTriggerId: ["17"],
        consentSettings: {
          consentStatus: "notSet",
        },
      },
    ],
    builtInVariable: [
      {
        accountId: "6004731770",
        containerId: "265489931",
        type: "containerVersion",
        name: "Container Version",
      },
      {
        accountId: "6004731770",
        containerId: "265489931",
        type: "debugMode",
        name: "Debug Mode",
      },
      {
        accountId: "6004731770",
        containerId: "265489931",
        type: "randomNumber",
        name: "Random Number",
      },
      {
        accountId: "6004731770",
        containerId: "265489931",
        type: "containerId",
        name: "Container ID",
      },
      {
        accountId: "6004731770",
        containerId: "265489931",
        type: "eventName",
        name: "Event Name",
      },
      {
        accountId: "6004731770",
        containerId: "265489931",
        type: "requestPath",
        name: "Request Path",
      },
      {
        accountId: "6004731770",
        containerId: "265489931",
        type: "requestMethod",
        name: "Request Method",
      },
      {
        accountId: "6004731770",
        containerId: "265489931",
        type: "clientName",
        name: "Client Name",
      },
      {
        accountId: "6004731770",
        containerId: "265489931",
        type: "queryString",
        name: "Query String",
      },
      {
        accountId: "6004731770",
        containerId: "265489931",
        type: "visitorRegion",
        name: "Visitor Region",
      },
    ],
    gtagConfig: [],
    customTemplate: [],
    client: [
      {
        accountId: "6004731770",
        containerId: "265489931",
        clientId: "1",
        name: "GA4",
        type: "gaaw_client",
        parameter: [
          {
            type: "template",
            key: "cookieDomain",
            value: "auto",
          },
          {
            type: "template",
            key: "cookieMaxAgeInSec",
            value: "63072000",
          },
          {
            type: "boolean",
            key: "activateDefaultPaths",
            value: "true",
          },
          {
            type: "template",
            key: "cookiePath",
            value: "/",
          },
          {
            type: "template",
            key: "cookieManagement",
            value: "server",
          },
          {
            type: "template",
            key: "cookieName",
            value: "FPID",
          },
        ],
        fingerprint: "1790640093583",
        notes:
          'Claims the GA4 hits the web container\'s Google tag sends to this tagging server and keeps the client id in a server-set FPID cookie.\n---\n{"recipes":["ga4_client"]}',
      },
      {
        accountId: "6004731770",
        containerId: "265489931",
        clientId: "12",
        name: "GTM",
        type: "gtm_client",
        parameter: [
          {
            type: "boolean",
            key: "activateResponseCompression",
            value: "true",
          },
          {
            type: "boolean",
            key: "isPathMandatory",
            value: "false",
          },
          {
            type: "boolean",
            key: "activateGeoResolution",
            value: "false",
          },
          {
            type: "list",
            key: "allowedContainerIds",
            list: [
              {
                type: "map",
                map: [
                  {
                    type: "template",
                    key: "containerId",
                    value: "{{Const - Web Container ID}}",
                  },
                  {
                    type: "template",
                    key: "path",
                  },
                ],
              },
            ],
          },
        ],
        fingerprint: "1790640098589",
        notes:
          'Serves the web container\'s gtm.js from the tagging server\'s first-party domain.\n---\n{"recipes":["web_container_client"]}',
      },
    ],
    transformation: [],
  },
  manifest: {
    conventions: {},
    recipes: {
      ga4_client: {
        description: "GA4 client, GA4 forwarding, Conversion Linker; base for every recipe.",
      },
      contact_form_submit: {
        description: "Contact form submitted.",
        dependencies: [
          {
            constant: "Const - Google Ads - contact_form_submit Conversion Label",
            platform: "googleAds",
            resource: "conversionAction",
          },
        ],
      },
      call_click: {
        description: "tel: link clicked.",
        dependencies: [
          {
            constant: "Const - Google Ads - call_click Conversion Label",
            platform: "googleAds",
            resource: "conversionAction",
          },
        ],
      },
      email_click: {
        description: "mailto: link clicked.",
        dependencies: [
          {
            constant: "Const - Google Ads - email_click Conversion Label",
            platform: "googleAds",
            resource: "conversionAction",
          },
        ],
      },
      maps_click: {
        description: "Google Maps link clicked.",
        dependencies: [
          {
            constant: "Const - Google Ads - maps_click Conversion Label",
            platform: "googleAds",
            resource: "conversionAction",
          },
        ],
      },
      web_container_client: {
        description: "Serves the web container's gtm.js first-party.",
      },
    },
  },
  encoding: {
    name: "notes",
  },
  metadata: {
    "variable:Const - Google Ads Conversion ID": {
      placeholder: {
        kind: "adsConversionId",
        example: "123456789",
        pattern: "^[0-9]+$",
      },
    },
    "variable:Const - Google Ads - contact_form_submit Conversion Label": {
      placeholder: {
        kind: "adsConversionLabel",
        example: "AbCdEfGhIjKlMnOp",
        pattern: "^[A-Za-z0-9_-]{5,}$",
      },
    },
    "variable:Const - Google Ads - call_click Conversion Label": {
      placeholder: {
        kind: "adsConversionLabel",
        example: "AbCdEfGhIjKlMnOp",
        pattern: "^[A-Za-z0-9_-]{5,}$",
      },
    },
    "variable:Const - Google Ads - email_click Conversion Label": {
      placeholder: {
        kind: "adsConversionLabel",
        example: "AbCdEfGhIjKlMnOp",
        pattern: "^[A-Za-z0-9_-]{5,}$",
      },
    },
    "variable:Const - Google Ads - maps_click Conversion Label": {
      placeholder: {
        kind: "adsConversionLabel",
        example: "AbCdEfGhIjKlMnOp",
        pattern: "^[A-Za-z0-9_-]{5,}$",
      },
    },
    "variable:Const - Web Container ID": {
      placeholder: {
        kind: "gtmPublicId",
        example: "GTM-ABC1234",
        pattern: "^GTM-[A-Z0-9]+$",
      },
    },
    "tag:GA4 - All Events": {
      recipes: ["ga4_client"],
    },
    "tag:Conversion Linker": {
      recipes: ["ga4_client"],
    },
    "tag:Ads - contact_form_submit": {
      recipes: ["contact_form_submit"],
    },
    "tag:Ads - call_click": {
      recipes: ["call_click"],
    },
    "tag:Ads - email_click": {
      recipes: ["email_click"],
    },
    "tag:Ads - maps_click": {
      recipes: ["maps_click"],
    },
    "client:GA4": {
      recipes: ["ga4_client"],
    },
    "client:GTM": {
      recipes: ["web_container_client"],
    },
  },
  recipes: [
    {
      name: "ga4_client",
      description: "GA4 client, GA4 forwarding, Conversion Linker; base for every recipe.",
      roots: [
        {
          kind: "tag",
          name: "GA4 - All Events",
        },
        {
          kind: "tag",
          name: "Conversion Linker",
        },
        {
          kind: "client",
          name: "GA4",
        },
      ],
      entities: [
        {
          kind: "tag",
          name: "GA4 - All Events",
        },
        {
          kind: "tag",
          name: "Conversion Linker",
        },
        {
          kind: "client",
          name: "GA4",
        },
        {
          kind: "trigger",
          name: "Client - GA4",
        },
        {
          kind: "trigger",
          name: "All Pages",
        },
        {
          kind: "builtInVariable",
          name: "clientName",
        },
      ],
      dependencies: [],
      conflicts: [],
    },
    {
      name: "contact_form_submit",
      description: "Contact form submitted.",
      roots: [
        {
          kind: "tag",
          name: "Ads - contact_form_submit",
        },
      ],
      entities: [
        {
          kind: "tag",
          name: "Ads - contact_form_submit",
        },
        {
          kind: "trigger",
          name: "Custom Event - contact_form_submit",
        },
        {
          kind: "variable",
          name: "Const - Google Ads Conversion ID",
        },
        {
          kind: "variable",
          name: "Const - Google Ads - contact_form_submit Conversion Label",
        },
        {
          kind: "client",
          name: "GA4",
        },
        {
          kind: "builtInVariable",
          name: "clientName",
        },
      ],
      dependencies: [
        {
          constant: "Const - Google Ads - contact_form_submit Conversion Label",
          platform: "googleAds",
          resource: "conversionAction",
        },
      ],
      conflicts: [],
    },
    {
      name: "call_click",
      description: "tel: link clicked.",
      roots: [
        {
          kind: "tag",
          name: "Ads - call_click",
        },
      ],
      entities: [
        {
          kind: "tag",
          name: "Ads - call_click",
        },
        {
          kind: "trigger",
          name: "Custom Event - call_click",
        },
        {
          kind: "variable",
          name: "Const - Google Ads Conversion ID",
        },
        {
          kind: "variable",
          name: "Const - Google Ads - call_click Conversion Label",
        },
        {
          kind: "client",
          name: "GA4",
        },
        {
          kind: "builtInVariable",
          name: "clientName",
        },
      ],
      dependencies: [
        {
          constant: "Const - Google Ads - call_click Conversion Label",
          platform: "googleAds",
          resource: "conversionAction",
        },
      ],
      conflicts: [],
    },
    {
      name: "email_click",
      description: "mailto: link clicked.",
      roots: [
        {
          kind: "tag",
          name: "Ads - email_click",
        },
      ],
      entities: [
        {
          kind: "tag",
          name: "Ads - email_click",
        },
        {
          kind: "trigger",
          name: "Custom Event - email_click",
        },
        {
          kind: "variable",
          name: "Const - Google Ads Conversion ID",
        },
        {
          kind: "variable",
          name: "Const - Google Ads - email_click Conversion Label",
        },
        {
          kind: "client",
          name: "GA4",
        },
        {
          kind: "builtInVariable",
          name: "clientName",
        },
      ],
      dependencies: [
        {
          constant: "Const - Google Ads - email_click Conversion Label",
          platform: "googleAds",
          resource: "conversionAction",
        },
      ],
      conflicts: [],
    },
    {
      name: "maps_click",
      description: "Google Maps link clicked.",
      roots: [
        {
          kind: "tag",
          name: "Ads - maps_click",
        },
      ],
      entities: [
        {
          kind: "tag",
          name: "Ads - maps_click",
        },
        {
          kind: "trigger",
          name: "Custom Event - maps_click",
        },
        {
          kind: "variable",
          name: "Const - Google Ads Conversion ID",
        },
        {
          kind: "variable",
          name: "Const - Google Ads - maps_click Conversion Label",
        },
        {
          kind: "client",
          name: "GA4",
        },
        {
          kind: "builtInVariable",
          name: "clientName",
        },
      ],
      dependencies: [
        {
          constant: "Const - Google Ads - maps_click Conversion Label",
          platform: "googleAds",
          resource: "conversionAction",
        },
      ],
      conflicts: [],
    },
    {
      name: "web_container_client",
      description: "Serves the web container's gtm.js first-party.",
      roots: [
        {
          kind: "client",
          name: "GTM",
        },
      ],
      entities: [
        {
          kind: "client",
          name: "GTM",
        },
        {
          kind: "variable",
          name: "Const - Web Container ID",
        },
      ],
      dependencies: [],
      conflicts: [],
    },
  ],
} as const;
