// GENERATED by gtm-apply from a Tag Manager container. Do not edit; run the package's pull script.
export const data = {
  data: {
    pulledAt: "1970-01-01T00:00:00.000Z",
    source: {
      container: "GTM-SAMPLE",
    },
    container: {
      accountId: "1",
      containerId: "20",
      publicId: "GTM-SAMPLE",
      name: "Server Template (sample)",
      usageContext: ["server"],
      path: "accounts/1/containers/20",
    },
    containerType: "server",
    environments: [],
    destinations: [],
    workspace: null,
    containerVersionHeader: {
      containerVersionId: "22",
      path: "accounts/1/containers/20/versions/22",
      name: "sample",
      numTags: "6",
      numClients: "2",
    },
    environment: null,
    folder: [],
    variable: [
      {
        name: "Library - Manifest",
        type: "c",
        parameter: [
          {
            type: "template",
            key: "value",
            value:
              '{"conventions":{},"recipes":{"ga4_client":{"description":"GA4 client, a GA4 tag forwarding every claimed event, and the Conversion Linker; base for every recipe."},"contact_form_submit":{"description":"Google Ads conversion on the contact_form_submit event.","dependencies":[{"constant":"Const - Google Ads - contact_form_submit Conversion Label","platform":"googleAds","resource":"conversionAction"}]},"call_click":{"description":"Google Ads conversion on the call_click event.","dependencies":[{"constant":"Const - Google Ads - call_click Conversion Label","platform":"googleAds","resource":"conversionAction"}]},"email_click":{"description":"Google Ads conversion on the email_click event.","dependencies":[{"constant":"Const - Google Ads - email_click Conversion Label","platform":"googleAds","resource":"conversionAction"}]},"maps_click":{"description":"Google Ads conversion on the maps_click event.","dependencies":[{"constant":"Const - Google Ads - maps_click Conversion Label","platform":"googleAds","resource":"conversionAction"}]},"web_container_client":{"description":"Serves the web container first-party from the tagging server."}}}',
          },
        ],
        variableId: "2",
        path: "accounts/1/containers/20/workspace/1/variable/2",
        fingerprint: "1",
      },
      {
        name: "Const - Google Ads Conversion ID",
        type: "c",
        notes:
          'The bare numeric conversion id (the digits after AW- in Google Ads). GTM stores it without the prefix; the conversion tag builds AW-<id>/<label> itself.\n---\n{"placeholder":{"kind":"adsConversionId","example":"123456789","pattern":"^[0-9]+$"}}',
        parameter: [
          {
            type: "template",
            key: "value",
            value: "<XXXXXXXXX>",
          },
        ],
        variableId: "3",
        path: "accounts/1/containers/20/workspace/1/variable/3",
        fingerprint: "1",
      },
      {
        name: "Const - Google Ads - contact_form_submit Conversion Label",
        type: "c",
        notes:
          'Conversion label of the Google Ads conversion action for contact_form_submit.\n---\n{"placeholder":{"kind":"adsConversionLabel","example":"AbCdEfGhIjKlMnOp","pattern":"^[A-Za-z0-9_-]{5,}$"}}',
        parameter: [
          {
            type: "template",
            key: "value",
            value: "<label>",
          },
        ],
        variableId: "4",
        path: "accounts/1/containers/20/workspace/1/variable/4",
        fingerprint: "1",
      },
      {
        name: "Const - Google Ads - call_click Conversion Label",
        type: "c",
        notes:
          'Conversion label of the Google Ads conversion action for call_click.\n---\n{"placeholder":{"kind":"adsConversionLabel","example":"AbCdEfGhIjKlMnOp","pattern":"^[A-Za-z0-9_-]{5,}$"}}',
        parameter: [
          {
            type: "template",
            key: "value",
            value: "<label>",
          },
        ],
        variableId: "5",
        path: "accounts/1/containers/20/workspace/1/variable/5",
        fingerprint: "1",
      },
      {
        name: "Const - Google Ads - email_click Conversion Label",
        type: "c",
        notes:
          'Conversion label of the Google Ads conversion action for email_click.\n---\n{"placeholder":{"kind":"adsConversionLabel","example":"AbCdEfGhIjKlMnOp","pattern":"^[A-Za-z0-9_-]{5,}$"}}',
        parameter: [
          {
            type: "template",
            key: "value",
            value: "<label>",
          },
        ],
        variableId: "6",
        path: "accounts/1/containers/20/workspace/1/variable/6",
        fingerprint: "1",
      },
      {
        name: "Const - Google Ads - maps_click Conversion Label",
        type: "c",
        notes:
          'Conversion label of the Google Ads conversion action for maps_click.\n---\n{"placeholder":{"kind":"adsConversionLabel","example":"AbCdEfGhIjKlMnOp","pattern":"^[A-Za-z0-9_-]{5,}$"}}',
        parameter: [
          {
            type: "template",
            key: "value",
            value: "<label>",
          },
        ],
        variableId: "7",
        path: "accounts/1/containers/20/workspace/1/variable/7",
        fingerprint: "1",
      },
      {
        name: "Const - Web Container ID",
        type: "c",
        notes:
          'Public id of the web container this tagging server serves.\n---\n{"placeholder":{"kind":"gtmPublicId","example":"GTM-ABC1234","pattern":"^GTM-[A-Z0-9]+$"}}',
        parameter: [
          {
            type: "template",
            key: "value",
            value: "<GTM-XXXXXXX>",
          },
        ],
        variableId: "8",
        path: "accounts/1/containers/20/workspace/1/variable/8",
        fingerprint: "1",
      },
    ],
    trigger: [
      {
        name: "Client - GA4",
        type: "always",
        notes: "Fires for every event the GA4 client claims.",
        filter: [
          {
            type: "equals",
            parameter: [
              {
                type: "template",
                key: "arg0",
                value: "{{Client Name}}",
              },
              {
                type: "template",
                key: "arg1",
                value: "GA4",
              },
            ],
          },
        ],
        triggerId: "11",
        path: "accounts/1/containers/20/workspace/1/trigger/11",
        fingerprint: "1",
      },
      {
        name: "Custom Event - contact_form_submit",
        type: "customEvent",
        notes:
          "Fires when the GA4 client claims the contact_form_submit event sent by the web container.",
        customEventFilter: [
          {
            type: "equals",
            parameter: [
              {
                type: "template",
                key: "arg0",
                value: "{{_event}}",
              },
              {
                type: "template",
                key: "arg1",
                value: "contact_form_submit",
              },
            ],
          },
        ],
        filter: [
          {
            type: "equals",
            parameter: [
              {
                type: "template",
                key: "arg0",
                value: "{{Client Name}}",
              },
              {
                type: "template",
                key: "arg1",
                value: "GA4",
              },
            ],
          },
        ],
        triggerId: "12",
        path: "accounts/1/containers/20/workspace/1/trigger/12",
        fingerprint: "1",
      },
      {
        name: "Custom Event - call_click",
        type: "customEvent",
        notes: "Fires when the GA4 client claims the call_click event sent by the web container.",
        customEventFilter: [
          {
            type: "equals",
            parameter: [
              {
                type: "template",
                key: "arg0",
                value: "{{_event}}",
              },
              {
                type: "template",
                key: "arg1",
                value: "call_click",
              },
            ],
          },
        ],
        filter: [
          {
            type: "equals",
            parameter: [
              {
                type: "template",
                key: "arg0",
                value: "{{Client Name}}",
              },
              {
                type: "template",
                key: "arg1",
                value: "GA4",
              },
            ],
          },
        ],
        triggerId: "13",
        path: "accounts/1/containers/20/workspace/1/trigger/13",
        fingerprint: "1",
      },
      {
        name: "Custom Event - email_click",
        type: "customEvent",
        notes: "Fires when the GA4 client claims the email_click event sent by the web container.",
        customEventFilter: [
          {
            type: "equals",
            parameter: [
              {
                type: "template",
                key: "arg0",
                value: "{{_event}}",
              },
              {
                type: "template",
                key: "arg1",
                value: "email_click",
              },
            ],
          },
        ],
        filter: [
          {
            type: "equals",
            parameter: [
              {
                type: "template",
                key: "arg0",
                value: "{{Client Name}}",
              },
              {
                type: "template",
                key: "arg1",
                value: "GA4",
              },
            ],
          },
        ],
        triggerId: "14",
        path: "accounts/1/containers/20/workspace/1/trigger/14",
        fingerprint: "1",
      },
      {
        name: "Custom Event - maps_click",
        type: "customEvent",
        notes: "Fires when the GA4 client claims the maps_click event sent by the web container.",
        customEventFilter: [
          {
            type: "equals",
            parameter: [
              {
                type: "template",
                key: "arg0",
                value: "{{_event}}",
              },
              {
                type: "template",
                key: "arg1",
                value: "maps_click",
              },
            ],
          },
        ],
        filter: [
          {
            type: "equals",
            parameter: [
              {
                type: "template",
                key: "arg0",
                value: "{{Client Name}}",
              },
              {
                type: "template",
                key: "arg1",
                value: "GA4",
              },
            ],
          },
        ],
        triggerId: "15",
        path: "accounts/1/containers/20/workspace/1/trigger/15",
        fingerprint: "1",
      },
    ],
    tag: [
      {
        name: "GA4 - All Events",
        type: "sgtmgaaw",
        notes:
          'Forwards every event the GA4 client claims to GA4. Its fields stay at their defaults, so it inherits the measurement id and parameters from each event (https://developers.google.com/tag-platform/learn/sst-fundamentals/5-sst-setup-analytics).\n---\n{"recipes":["ga4_client"]}',
        parameter: [
          {
            type: "template",
            key: "epToIncludeDropdown",
            value: "all",
          },
          {
            type: "template",
            key: "upToIncludeDropdown",
            value: "all",
          },
          {
            type: "boolean",
            key: "redactVisitorIp",
            value: "false",
          },
        ],
        firingTriggerId: ["11"],
        tagId: "16",
        path: "accounts/1/containers/20/workspace/1/tag/16",
        fingerprint: "1",
      },
      {
        name: "Conversion Linker",
        type: "sgtmadscl",
        notes:
          'Sets the Google Ads click cookies from the tagging server.\n---\n{"recipes":["ga4_client"]}',
        parameter: [
          {
            type: "boolean",
            key: "enableLinkerParams",
            value: "false",
          },
          {
            type: "boolean",
            key: "enableCookieOverrides",
            value: "false",
          },
        ],
        firingTriggerId: ["2147479574"],
        tagId: "17",
        path: "accounts/1/containers/20/workspace/1/tag/17",
        fingerprint: "1",
      },
      {
        name: "Ads - contact_form_submit",
        type: "sgtmadsct",
        notes:
          'Records the contact_form_submit conversion in Google Ads from the tagging server.\n---\n{"recipes":["contact_form_submit"]}',
        parameter: [
          {
            type: "template",
            key: "conversionId",
            value: "{{Const - Google Ads Conversion ID}}",
          },
          {
            type: "template",
            key: "conversionLabel",
            value: "{{Const - Google Ads - contact_form_submit Conversion Label}}",
          },
          {
            type: "boolean",
            key: "enableConversionLinker",
            value: "true",
          },
          {
            type: "boolean",
            key: "enableProductReporting",
            value: "false",
          },
          {
            type: "boolean",
            key: "enableNewCustomerReporting",
            value: "false",
          },
          {
            type: "boolean",
            key: "rdp",
            value: "false",
          },
        ],
        firingTriggerId: ["12"],
        tagId: "18",
        path: "accounts/1/containers/20/workspace/1/tag/18",
        fingerprint: "1",
      },
      {
        name: "Ads - call_click",
        type: "sgtmadsct",
        notes:
          'Records the call_click conversion in Google Ads from the tagging server.\n---\n{"recipes":["call_click"]}',
        parameter: [
          {
            type: "template",
            key: "conversionId",
            value: "{{Const - Google Ads Conversion ID}}",
          },
          {
            type: "template",
            key: "conversionLabel",
            value: "{{Const - Google Ads - call_click Conversion Label}}",
          },
          {
            type: "boolean",
            key: "enableConversionLinker",
            value: "true",
          },
          {
            type: "boolean",
            key: "enableProductReporting",
            value: "false",
          },
          {
            type: "boolean",
            key: "enableNewCustomerReporting",
            value: "false",
          },
          {
            type: "boolean",
            key: "rdp",
            value: "false",
          },
        ],
        firingTriggerId: ["13"],
        tagId: "19",
        path: "accounts/1/containers/20/workspace/1/tag/19",
        fingerprint: "1",
      },
      {
        name: "Ads - email_click",
        type: "sgtmadsct",
        notes:
          'Records the email_click conversion in Google Ads from the tagging server.\n---\n{"recipes":["email_click"]}',
        parameter: [
          {
            type: "template",
            key: "conversionId",
            value: "{{Const - Google Ads Conversion ID}}",
          },
          {
            type: "template",
            key: "conversionLabel",
            value: "{{Const - Google Ads - email_click Conversion Label}}",
          },
          {
            type: "boolean",
            key: "enableConversionLinker",
            value: "true",
          },
          {
            type: "boolean",
            key: "enableProductReporting",
            value: "false",
          },
          {
            type: "boolean",
            key: "enableNewCustomerReporting",
            value: "false",
          },
          {
            type: "boolean",
            key: "rdp",
            value: "false",
          },
        ],
        firingTriggerId: ["14"],
        tagId: "20",
        path: "accounts/1/containers/20/workspace/1/tag/20",
        fingerprint: "1",
      },
      {
        name: "Ads - maps_click",
        type: "sgtmadsct",
        notes:
          'Records the maps_click conversion in Google Ads from the tagging server.\n---\n{"recipes":["maps_click"]}',
        parameter: [
          {
            type: "template",
            key: "conversionId",
            value: "{{Const - Google Ads Conversion ID}}",
          },
          {
            type: "template",
            key: "conversionLabel",
            value: "{{Const - Google Ads - maps_click Conversion Label}}",
          },
          {
            type: "boolean",
            key: "enableConversionLinker",
            value: "true",
          },
          {
            type: "boolean",
            key: "enableProductReporting",
            value: "false",
          },
          {
            type: "boolean",
            key: "enableNewCustomerReporting",
            value: "false",
          },
          {
            type: "boolean",
            key: "rdp",
            value: "false",
          },
        ],
        firingTriggerId: ["15"],
        tagId: "21",
        path: "accounts/1/containers/20/workspace/1/tag/21",
        fingerprint: "1",
      },
    ],
    builtInVariable: [
      {
        type: "clientName",
      },
    ],
    gtagConfig: [],
    customTemplate: [],
    client: [
      {
        name: "GA4",
        type: "gaaw_client",
        notes:
          'Claims the GA4 hits the web container\'s Google tag sends to this tagging server and keeps the client id in a server-set FPID cookie.\n---\n{"recipes":["ga4_client"]}',
        parameter: [
          {
            type: "boolean",
            key: "activateDefaultPaths",
            value: "true",
          },
          {
            type: "template",
            key: "cookieManagement",
            value: "server",
          },
          {
            type: "template",
            key: "cookieName",
            value: "FPID",
          },
          {
            type: "template",
            key: "cookieDomain",
            value: "auto",
          },
          {
            type: "template",
            key: "cookiePath",
            value: "/",
          },
          {
            type: "template",
            key: "cookieMaxAgeInSec",
            value: "63072000",
          },
        ],
        clientId: "9",
        path: "accounts/1/containers/20/workspace/1/client/9",
        fingerprint: "1",
      },
      {
        name: "GTM",
        type: "gtm_client",
        notes:
          'Serves the web container\'s gtm.js from the tagging server\'s first-party domain.\n---\n{"recipes":["web_container_client"]}',
        parameter: [
          {
            type: "list",
            key: "allowedContainerIds",
            list: [
              {
                type: "map",
                map: [
                  {
                    type: "template",
                    key: "containerId",
                    value: "{{Const - Web Container ID}}",
                  },
                ],
              },
            ],
          },
          {
            type: "boolean",
            key: "activateResponseCompression",
            value: "true",
          },
          {
            type: "boolean",
            key: "activateDependencyServing",
            value: "true",
          },
          {
            type: "boolean",
            key: "activateGeoResolution",
            value: "false",
          },
        ],
        clientId: "10",
        path: "accounts/1/containers/20/workspace/1/client/10",
        fingerprint: "1",
      },
    ],
    transformation: [],
  },
  manifest: {
    conventions: {},
    recipes: {
      ga4_client: {
        description:
          "GA4 client, a GA4 tag forwarding every claimed event, and the Conversion Linker; base for every recipe.",
      },
      contact_form_submit: {
        description: "Google Ads conversion on the contact_form_submit event.",
        dependencies: [
          {
            constant: "Const - Google Ads - contact_form_submit Conversion Label",
            platform: "googleAds",
            resource: "conversionAction",
          },
        ],
      },
      call_click: {
        description: "Google Ads conversion on the call_click event.",
        dependencies: [
          {
            constant: "Const - Google Ads - call_click Conversion Label",
            platform: "googleAds",
            resource: "conversionAction",
          },
        ],
      },
      email_click: {
        description: "Google Ads conversion on the email_click event.",
        dependencies: [
          {
            constant: "Const - Google Ads - email_click Conversion Label",
            platform: "googleAds",
            resource: "conversionAction",
          },
        ],
      },
      maps_click: {
        description: "Google Ads conversion on the maps_click event.",
        dependencies: [
          {
            constant: "Const - Google Ads - maps_click Conversion Label",
            platform: "googleAds",
            resource: "conversionAction",
          },
        ],
      },
      web_container_client: {
        description: "Serves the web container first-party from the tagging server.",
      },
    },
  },
  encoding: {
    name: "notes",
  },
  metadata: {
    "variable:Const - Google Ads Conversion ID": {
      placeholder: {
        kind: "adsConversionId",
        example: "123456789",
        pattern: "^[0-9]+$",
      },
    },
    "variable:Const - Google Ads - contact_form_submit Conversion Label": {
      placeholder: {
        kind: "adsConversionLabel",
        example: "AbCdEfGhIjKlMnOp",
        pattern: "^[A-Za-z0-9_-]{5,}$",
      },
    },
    "variable:Const - Google Ads - call_click Conversion Label": {
      placeholder: {
        kind: "adsConversionLabel",
        example: "AbCdEfGhIjKlMnOp",
        pattern: "^[A-Za-z0-9_-]{5,}$",
      },
    },
    "variable:Const - Google Ads - email_click Conversion Label": {
      placeholder: {
        kind: "adsConversionLabel",
        example: "AbCdEfGhIjKlMnOp",
        pattern: "^[A-Za-z0-9_-]{5,}$",
      },
    },
    "variable:Const - Google Ads - maps_click Conversion Label": {
      placeholder: {
        kind: "adsConversionLabel",
        example: "AbCdEfGhIjKlMnOp",
        pattern: "^[A-Za-z0-9_-]{5,}$",
      },
    },
    "variable:Const - Web Container ID": {
      placeholder: {
        kind: "gtmPublicId",
        example: "GTM-ABC1234",
        pattern: "^GTM-[A-Z0-9]+$",
      },
    },
    "tag:GA4 - All Events": {
      recipes: ["ga4_client"],
    },
    "tag:Conversion Linker": {
      recipes: ["ga4_client"],
    },
    "tag:Ads - contact_form_submit": {
      recipes: ["contact_form_submit"],
    },
    "tag:Ads - call_click": {
      recipes: ["call_click"],
    },
    "tag:Ads - email_click": {
      recipes: ["email_click"],
    },
    "tag:Ads - maps_click": {
      recipes: ["maps_click"],
    },
    "client:GA4": {
      recipes: ["ga4_client"],
    },
    "client:GTM": {
      recipes: ["web_container_client"],
    },
  },
  recipes: [
    {
      name: "ga4_client",
      description:
        "GA4 client, a GA4 tag forwarding every claimed event, and the Conversion Linker; base for every recipe.",
      roots: [
        {
          kind: "tag",
          name: "GA4 - All Events",
        },
        {
          kind: "tag",
          name: "Conversion Linker",
        },
        {
          kind: "client",
          name: "GA4",
        },
      ],
      entities: [
        {
          kind: "tag",
          name: "GA4 - All Events",
        },
        {
          kind: "tag",
          name: "Conversion Linker",
        },
        {
          kind: "client",
          name: "GA4",
        },
        {
          kind: "trigger",
          name: "Client - GA4",
        },
        {
          kind: "trigger",
          name: "All Pages",
        },
        {
          kind: "builtInVariable",
          name: "clientName",
        },
      ],
      dependencies: [],
      conflicts: [],
    },
    {
      name: "contact_form_submit",
      description: "Google Ads conversion on the contact_form_submit event.",
      roots: [
        {
          kind: "tag",
          name: "Ads - contact_form_submit",
        },
      ],
      entities: [
        {
          kind: "tag",
          name: "Ads - contact_form_submit",
        },
        {
          kind: "trigger",
          name: "Custom Event - contact_form_submit",
        },
        {
          kind: "variable",
          name: "Const - Google Ads Conversion ID",
        },
        {
          kind: "variable",
          name: "Const - Google Ads - contact_form_submit Conversion Label",
        },
        {
          kind: "client",
          name: "GA4",
        },
        {
          kind: "builtInVariable",
          name: "clientName",
        },
      ],
      dependencies: [
        {
          constant: "Const - Google Ads - contact_form_submit Conversion Label",
          platform: "googleAds",
          resource: "conversionAction",
        },
      ],
      conflicts: [],
    },
    {
      name: "call_click",
      description: "Google Ads conversion on the call_click event.",
      roots: [
        {
          kind: "tag",
          name: "Ads - call_click",
        },
      ],
      entities: [
        {
          kind: "tag",
          name: "Ads - call_click",
        },
        {
          kind: "trigger",
          name: "Custom Event - call_click",
        },
        {
          kind: "variable",
          name: "Const - Google Ads Conversion ID",
        },
        {
          kind: "variable",
          name: "Const - Google Ads - call_click Conversion Label",
        },
        {
          kind: "client",
          name: "GA4",
        },
        {
          kind: "builtInVariable",
          name: "clientName",
        },
      ],
      dependencies: [
        {
          constant: "Const - Google Ads - call_click Conversion Label",
          platform: "googleAds",
          resource: "conversionAction",
        },
      ],
      conflicts: [],
    },
    {
      name: "email_click",
      description: "Google Ads conversion on the email_click event.",
      roots: [
        {
          kind: "tag",
          name: "Ads - email_click",
        },
      ],
      entities: [
        {
          kind: "tag",
          name: "Ads - email_click",
        },
        {
          kind: "trigger",
          name: "Custom Event - email_click",
        },
        {
          kind: "variable",
          name: "Const - Google Ads Conversion ID",
        },
        {
          kind: "variable",
          name: "Const - Google Ads - email_click Conversion Label",
        },
        {
          kind: "client",
          name: "GA4",
        },
        {
          kind: "builtInVariable",
          name: "clientName",
        },
      ],
      dependencies: [
        {
          constant: "Const - Google Ads - email_click Conversion Label",
          platform: "googleAds",
          resource: "conversionAction",
        },
      ],
      conflicts: [],
    },
    {
      name: "maps_click",
      description: "Google Ads conversion on the maps_click event.",
      roots: [
        {
          kind: "tag",
          name: "Ads - maps_click",
        },
      ],
      entities: [
        {
          kind: "tag",
          name: "Ads - maps_click",
        },
        {
          kind: "trigger",
          name: "Custom Event - maps_click",
        },
        {
          kind: "variable",
          name: "Const - Google Ads Conversion ID",
        },
        {
          kind: "variable",
          name: "Const - Google Ads - maps_click Conversion Label",
        },
        {
          kind: "client",
          name: "GA4",
        },
        {
          kind: "builtInVariable",
          name: "clientName",
        },
      ],
      dependencies: [
        {
          constant: "Const - Google Ads - maps_click Conversion Label",
          platform: "googleAds",
          resource: "conversionAction",
        },
      ],
      conflicts: [],
    },
    {
      name: "web_container_client",
      description: "Serves the web container first-party from the tagging server.",
      roots: [
        {
          kind: "client",
          name: "GTM",
        },
      ],
      entities: [
        {
          kind: "client",
          name: "GTM",
        },
        {
          kind: "variable",
          name: "Const - Web Container ID",
        },
      ],
      dependencies: [],
      conflicts: [],
    },
  ],
} as const;
